fix ording of patches

diff --git a/apply-patchsets b/apply-patchsets
--- a/apply-patchsets
+++ b/apply-patchsets
@@ -49,8 +49,8 @@ for dir in $(find "$patchdir/" -type d || printf 'WARN: No patchsets found.\n' >
 	if [ "$patchdir/" == "$dir" ]; then
 		continue
 	fi
-	for patch in $(find "$dir" -type f || printf "WARN: Error reading patchset $(echo $dir | rev | cut -d / -f 1 | rev) found.\n" >&2 ); do
-		
+	for patch in $(find "$dir" -type f | sort || printf "WARN: Error reading patchset $(echo $dir | rev | cut -d / -f 1 | rev) found.\n" >&2 ); do
+
 
 		if ! git -c user.name='Gluon Patch Manager' -c user.email='gluon@void.example.com' -c commit.gpgsign=false am --whitespace=nowarn --committer-date-is-author-date "$patch"; then
 			git am --abort
