Update apply-patchsets

diff --git a/apply-patchsets b/apply-patchsets
--- a/apply-patchsets
+++ b/apply-patchsets
@@ -47,7 +47,7 @@ for dir in $(find "$patchdir/" -type d || printf 'WARN: No patchsets found.\n' >
 	if [ "$patchdir/" == "$dir" ]; then
 		continue
 	fi
-	for patch in $(find "$dir" -type f >/dev/null 2>&1 || printf "WARN: No patches in patchset $(echo $dir | rev | cut -d / -f 1 | rev) found.\n" >&2 ); do
+	for patch in $(find "$dir" -type f || printf "WARN: Error reading patchset $(echo $dir | rev | cut -d / -f 1 | rev) found.\n" >&2 ); do
 		git checkout -B patching base
 
 		if ! git -c user.name='Gluon Patch Manager' -c user.email='gluon@void.example.com' -c commit.gpgsign=false am --whitespace=nowarn --committer-date-is-author-date "$patchdir/$dir/$patch"; then
